

# CONFIG_GPIO=y
# CONFIG_GPIO_EMUL=y

# # LVGL config
# CONFIG_LVGL=y
# CONFIG_LV_MEM_CUSTOM=y
# CONFIG_LV_USE_LOG=y
# CONFIG_LV_USE_LABEL=y
# CONFIG_LV_USE_BTN=y
# CONFIG_LV_USE_ARC=y
# CONFIG_LV_USE_IMG=y

# CONFIG_ENTROPY_GENERATOR=y