CONFIG_COMPILER_WARNINGS_AS_ERRORS=y

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_PROCESS_THREAD_CUSTOM_PRIORITY=y
CONFIG_LOG_PROCESS_THREAD_PRIORITY=3

CONFIG_SHELL=y
CONFIG_SHELL_THREAD_PRIORITY_OVERRIDE=y
#CONFIG_SHELL_VT100_COLORS=n

CONFIG_TESTMODE=n