CONFIG_LV_Z_MEM_POOL_SIZE=163840
CONFIG_LV_Z_SHELL=y
CONFIG_MAIN_STACK_SIZE=16384

CONFIG_GPIO=y
CONFIG_INPUT=y
CONFIG_LOG=y
CONFIG_SHELL=y

CONFIG_DISPLAY=y
CONFIG_EMUL=y
CONFIG_GPIO_EMUL=y
CONFIG_GPIO_EMUL_SDL=y
CONFIG_EMUL_LOG_LEVEL_DBG=y

# LVGL config
CONFIG_LVGL=y
CONFIG_LV_MEM_CUSTOM=y
CONFIG_LV_USE_LOG=y
CONFIG_LV_USE_LABEL=y
CONFIG_LV_USE_BTN=y
CONFIG_LV_USE_ARC=y
CONFIG_LV_USE_IMG=y

CONFIG_ENTROPY_GENERATOR=y